export const ETAPAS = [
  "ORCAMENTO",
  "PROJETO",
  "CORTE",
  "ACABAMENTO",
  "INSTALACAO",
  "ENTREGA",
  "ENCERRADO"
];

export const STATUS_POR_ETAPA = {
  ORCAMENTO: "ORCAMENTO",
  PROJETO: "PROJETO",
  CORTE: "EM_PRODUCAO",
  ACABAMENTO: "EM_ACABAMENTO",
  INSTALACAO: "EM_INSTALACAO",
  ENTREGA: "ENTREGUE",
  ENCERRADO: "FINALIZADO"
};
